# Editor completion
"$schema" = 'https://starship.rs/config-schema.json'

# Select custome color palette
"palette" = "catppuccin_mocha"

# Define terminal line format
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$fill \
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$aws\
$crystal\
$battery\
$time\
$cmd_duration\
$line_break\
$shell\
$character"""

# Status module
[character]
format = '$symbol '
success_symbol = '[](bold green)'
error_symbol = '[](bold red)'

# Username module
[username]
format = '[ $user]($style) '
style_user = "blue bold"
style_root = "red bold"
show_always = true

# Hostname module
[hostname]
format = '[ $ssh_symbol$hostname]($style) '
style = "bold mauve"
ssh_only = false
ssh_symbol = "󰖟 "

# Directory module config
[directory]
format = '[ $path]($style)[$read_only]($read_only_style) '
style = "bold peach"
read_only_style = "red"
truncate_to_repo = true
truncation_symbol = ".."
truncation_length = 2
read_only = " "
home_symbol = "~"

# Git branch module
[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
style = "bold maroon"
truncation_symbol = ".."
symbol = " "

# Git commit module
[git_commit]
format = '[\($hash$tag\)]($style) '
style = "bold green"
tag_symbol = '  '

#Git state module
[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bold yellow"

# Git status module
[git_status]
format = '$all_status $ahead_behind '
conflicted = "[ Conflicted](red) "
ahead = "[󰳡 Ahead](green)"
behind = "[󰳛 Behind](red)"
diverged = " [ Diverged](peach)"
up_to_date = "[ Up to date](green)"
untracked = " [ Untracked](peach)"
stashed = " [ Stashed](yellow]"
modified = " [󱅄 Modified](yellow)"
staged = '[ Staged ($count)](green)'
renamed = "[󰂮 Renamed](peach)"
deleted = "[ Deleted](red)"

# Command duration
[cmd_duration]
min_time = 0
format = '[ $duration]($style) '
style = 'dimmed text'
show_notifications = true
min_time_to_notify = 60_000

# Time module
[time]
format = '[󰥔 $time]($style) '
style = "subtext0"
time_format = "%H:%M"
disabled = false

# Battery indicator configuration
[battery]
full_symbol = "󰁹"
unknown_symbol = "󱉝"
empty_symbol = "󱉝"
format = '[$symbol$percentage]($style) '

[[battery.display]]
threshold = 10
style = 'bold red'
discharging_symbol = "󰂎"
charging_symbol = "󰢜 "

[[battery.display]]
threshold = 20
style = 'bold yellow'
discharging_symbol = "󰁻"
charging_symbol = "󰂆 "

[[battery.display]]
threshold = 40
style = 'yellow'
discharging_symbol = "󰁽"
charging_symbol = "󰂈 "

[[battery.display]]
threshold = 60
style = 'yellow'
discharging_symbol = "󰁿"
charging_symbol = "󰂉 "

[[battery.display]]
threshold = 80
style = 'green'
discharging_symbol = "󰂁"
charging_symbol = "󰂊 "

[[battery.display]]
threshold = 100
style = 'green'
discharging_symbol = "󰁹"
charging_symbol = "󰂅 "

# Fill config
[fill]
style = "dimmed subtext0"
symbol = "."

# Catppuccin Mocha Color Palette Definition
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

# Languages icons and formats# NerdFonts Icons Preset
[aws]
format = '[$symbol($profile )(\($region\) )(\[$duration\] )]($style)'
symbol = " "

[buf]
symbol = " "
format = '[$symbol($version )]($style)'

[c]
symbol = " "
format = '[$symbol($version(-$name)) ]($style)'

[cmake]
symbol = " "
format = '[$symbol($version )]($style)'

[conda]
symbol = " "
format = '[$symbol$environment]($style) '

[crystal]
symbol = " "
format = '[$symbol($version )]($style)'

[dart]
symbol = " "
format = '[$symbol($version )]($style)'

[docker_context]
symbol = " "
format = '[$symbol$context]($style)'

[elixir]
symbol = " "
format = '[$symbol($version \(OTP $otp_version\) )]($style)'

[elm]
symbol = " "
format = '[$symbol($version )]($style)'

[fennel]
symbol = " "
format = '[$symbol($version )]($style)'

[fossil_branch]
symbol = " "
format = '[$symbol$branch]($style) '

[golang]
symbol = " "
format = "[$symbol($version )]($style)"

[haskell]
symbol = " "
format = '[$symbol($version )]($style)'

[haxe]
symbol = " "
format = '[$symbol($version )]($style)'

[java]
symbol = " "
format = '[${symbol}(${version} )]($style)'

[julia]
symbol = " "
format = '[$symbol($version )]($style)'

[kotlin]
symbol = " "
format = '[$symbol($version )]($style)'

[lua]
symbol = " "
format = '[$symbol($version )]($style)'

[meson]
symbol = "󰔷 "
format = '[$symbol$project]($style)'

[nim]
symbol = "󰆥 "
format = '[$symbol($version )]($style)'

[nodejs]
symbol = " "
format = '[$symbol($version )]($style)'

[ocaml]
symbol = " "
format= '[$symbol($version )(\($switch_indicator$switch_name\) )]($style)'

[package]
symbol = "󰏗 "
format = '[$symbol$version]($style) '

[perl]
symbol = " "
format = '[$symbol($version )]($style)'

[php]
symbol = " "
format = '[$symbol($version )]($style)'

[python]
symbol = " "
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[rlang]
symbol = "󰟔 "
format = '[$symbol($version )]($style)'

[ruby]
symbol = " "
format = '[$symbol($version )]($style)'

[rust]
symbol = "󱘗 "
format = '[$symbol($version )]($style)'

[scala]
symbol = " "
format = '[${symbol}(${version} )]($style)'

[swift]
symbol = " "
format = '[$symbol($version )]($style)'

[zig]
symbol = " "
format = '[$symbol($version )]($style)'

[gradle]
symbol = " "
format = '[$symbol($version )]($style)'

